[package]
name = "dns"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "dns"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
nom = "7.1"
byteorder = "1.4.3"
rand = "0.8.5"
bytes = "1.4.0"